version: '3.2'
services:
  consul:
    image: consul:0.9.3
    command: agent -dev -client "0.0.0.0"
    ports:
      - "8500:8500"
  orazio:
    build: .
    ports:
      - "8080:8080"
  calliope:
    build:
      context: ./pkg/muse/calliope
    ports:
      - "9090:9090"
